[phases.setup]
nixPkgs = ["python3", "make", "g++"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npx prisma generate && npm run build"

[start]
cmd = "npx prisma db push --accept-data-loss && node prisma/seed.js && npx next start -p ${PORT:-3000} -H 0.0.0.0"
