// Reads from imo_problems.json (generated by fetch_imo.js)
// If the file does not exist, fetches from mathnet.mit.edu
const fs = require('fs');
const path = 'imo_problems.json';

async function main() {
  const { PrismaClient } = require('@prisma/client');
  const checkPrisma = new PrismaClient();
  const existingCount = await checkPrisma.problem.count();
  if (existingCount > 0) {
    console.log('Problems already exist (' + existingCount + '), skipping seed to preserve data.');
    await checkPrisma.$disconnect();
    return;
  }
  await checkPrisma.$disconnect();
  let problems;
  
  if (fs.existsSync(path)) {
    problems = JSON.parse(fs.readFileSync(path, 'utf-8'));
    console.log('Loaded ' + problems.length + ' problems from ' + path);
  } else {
    console.log(path + ' not found, fetching from mathnet.mit.edu...');
    const { execSync } = require('child_process');
    execSync('node fetch_imo.js', { stdio: 'inherit' });
    problems = JSON.parse(fs.readFileSync(path, 'utf-8'));
  }

  const prisma = new PrismaClient();

  // Clear old data in order (child tables first)
  await prisma.xpLog.deleteMany();
  await prisma.redo.deleteMany();
        await prisma.transaction.deleteMany();
  await prisma.message.deleteMany();
  await prisma.submission.deleteMany();
  await prisma.userXp.deleteMany();
  await prisma.problem.deleteMany();
  console.log('Cleared old problems');

  for (const p of problems) {
    await prisma.problem.create({
      data: {
        title: p.year + 'IMOSL' + p.category + p.num,
        categoryId: p.category,
        difficultyId: p.star,
        problemImages: '[]',
        problemText: p.text,
        answerText: (p.solutions && p.solutions.length > 0) ? p.solutions.join("\n\n---\n\n") : null,
        answerImages: '[]',
        createdBy: 1,
      },
    });
  }

  const byStar = {};
  const byCat = {};
  for (const p of problems) {
    byStar[p.star] = (byStar[p.star] || 0) + 1;
    byCat[p.category] = (byCat[p.category] || 0) + 1;
  }
  console.log('Stars:', JSON.stringify(byStar));
  console.log('Cats:', JSON.stringify(byCat));
  console.log('✅ ' + problems.length + ' problems imported!');
  await prisma.$disconnect();
}
main().catch(e => { console.error(e.message); process.exit(1); });
